# -*- coding: utf-8 -*-
"""Small helper for manually reviewing and editing auto-generated YOLO labels."""

import argparse
from pathlib import Path

import cv2


HERE = Path(__file__).parent
DATASET_DIR = HERE / "yolo_dataset"
NAMES = ["1NT", "5NT", "10NT", "50NT"]
COLORS = [(255, 90, 90), (70, 220, 70), (0, 170, 255), (220, 80, 220)]


def resolve_stem(value):
    p = Path(value)
    name = p.name
    if name.endswith("_preview.jpg"):
        name = name[:-12] + ".jpg"
    if name.endswith("_numbered.jpg"):
        name = name[:-13] + ".jpg"
    if name.endswith(".txt"):
        name = name[:-4] + ".jpg"
    return Path(name).stem


def paths_for(stem, split="train"):
    return {
        "image": DATASET_DIR / "images" / split / f"{stem}.jpg",
        "label": DATASET_DIR / "labels" / split / f"{stem}.txt",
        "preview": DATASET_DIR / "previews" / split / f"{stem}_preview.jpg",
        "numbered": DATASET_DIR / "previews" / split / f"{stem}_numbered.jpg",
    }


def read_labels(label_path):
    if not label_path.exists():
        return []
    return [line.strip() for line in label_path.read_text(encoding="utf-8").splitlines() if line.strip()]


def draw_preview(stem, split="train", numbered=False):
    paths = paths_for(stem, split)
    img = cv2.imread(str(paths["image"]))
    if img is None:
        raise FileNotFoundError(paths["image"])
    h, w = img.shape[:2]
    lines = read_labels(paths["label"])
    for i, line in enumerate(lines, 1):
        parts = line.split()
        if len(parts) < 5:
            continue
        cls = int(float(parts[0]))
        xc, yc, bw, bh = map(float, parts[1:5])
        x1 = int(round((xc - bw / 2.0) * w))
        y1 = int(round((yc - bh / 2.0) * h))
        x2 = int(round((xc + bw / 2.0) * w))
        y2 = int(round((yc + bh / 2.0) * h))
        color = COLORS[cls] if 0 <= cls < len(COLORS) else (0, 255, 255)
        label = NAMES[cls] if 0 <= cls < len(NAMES) else str(cls)
        if numbered:
            label = f"{i}:{label}"
        cv2.rectangle(img, (x1, y1), (x2, y2), color, 2, cv2.LINE_AA)
        cv2.putText(img, label, (x1, max(18, y1 - 6)), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2, cv2.LINE_AA)
    out_path = paths["numbered"] if numbered else paths["preview"]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    cv2.imwrite(str(out_path), img)
    return out_path


def delete_indices(stem, indices, split="train"):
    paths = paths_for(stem, split)
    lines = read_labels(paths["label"])
    remove = {int(i) for i in indices}
    kept = [line for i, line in enumerate(lines, 1) if i not in remove]
    paths["label"].write_text("\n".join(kept) + ("\n" if kept else ""), encoding="utf-8")
    draw_preview(stem, split, numbered=False)
    numbered = draw_preview(stem, split, numbered=True)
    return len(lines) - len(kept), numbered


def main():
    parser = argparse.ArgumentParser(description="Review/edit YOLO labels generated by CoinVision.")
    parser.add_argument("sample", help="Image, label, preview filename, or stem such as quality_20260510_154213")
    parser.add_argument("--split", default="train", choices=["train", "val"])
    parser.add_argument("--numbered", action="store_true", help="Create a numbered preview image.")
    parser.add_argument("--delete", nargs="*", type=int, help="Delete one or more 1-based label indices.")
    args = parser.parse_args()

    stem = resolve_stem(args.sample)
    if args.delete:
        deleted, numbered = delete_indices(stem, args.delete, args.split)
        print(f"deleted={deleted}")
        print(numbered)
        return
    out = draw_preview(stem, args.split, numbered=True if args.numbered else False)
    print(out)


if __name__ == "__main__":
    main()
